name: Make downloads container
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  build-download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Free disk space
      run: |
        curl -L -k https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.download
        push: true
        tags: ghcr.io/${{ github.actor }}/stable-diffusion:downloads