name: Publish Docker
on: [push]
jobs:
  build-auto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Free disk space
      run: |
        curl -L -k https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.actor }}/stable-diffusion
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile.auto
        cache: true
        tags: auto
        platforms: linux/amd64
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to Docker Hub
      run: |
        docker buildx imagetools create \
          --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stable-diffusion:auto \
          ghcr.io/${{ github.actor }}/stable-diffusion:auto
  build-invoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Free disk space
      run: |
        curl -L -k https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.actor }}/stable-diffusion
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile.invoke
        cache: true
        tags: invoke
        platforms: linux/amd64
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to Docker Hub
      run: |
        docker buildx imagetools create \
          --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stable-diffusion:invoke \
          ghcr.io/${{ github.actor }}/stable-diffusion:invoke
