name: Publish Docker
on: [push]
jobs:
  build-auto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.auto
        push: true
        tags: ghcr.io/${{ github.actor }}/stable-diffusion:auto
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: DOWNIMAGE=ghcr.io/${{ github.actor }}/stable-diffusion:downloads
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to Docker Hub
      run: |
        docker buildx imagetools create \
          --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stable-diffusion:auto \
          ghcr.io/${{ github.actor }}/stable-diffusion:auto
  build-invoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.invoke
        push: true
        tags: ghcr.io/${{ github.actor }}/stable-diffusion:invoke
        build-args: DOWNIMAGE=ghcr.io/${{ github.actor }}/stable-diffusion:downloads
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to Docker Hub
      run: |
        docker buildx imagetools create \
          --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stable-diffusion:invoke \
          ghcr.io/${{ github.actor }}/stable-diffusion:invoke
